Add debug logger to unwrapped_line
This proved useful while I was working on the SPACE_INSIDE_BRACKETS and
SPACES_AROUND_SUBSCRIPT_COLON knobs, so I thought it might be useful for
others in the future.

The main use for me was, e.g.
```console
% nosetests \
    --logging-format="\%(filename)s:\%(lineno)d:\%(message)s" \
    yapftests/reformatter_pep8_test.py
...
AssertionError: Code format mismatch:
...
-------------------- >> begin captured logging << --------------------
unwrapped_line.py:285:
  'a', '='
  left:[FormatToken(name=NAME, value=a, lineno=1), '{NONE}'],
  right:[FormatToken(name=EQUAL, value==, lineno=1), '{ASSIGN_OPERATOR}']
unwrapped_line.py:524:space required
...
```