ci.yml: Stop CI from trying Python 3.7 on arm64 macOS
Symptom was this error:
> Error: The version '3.7' with architecture 'arm64' was not found for macOS 14.6.1.
> The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Note that Python 3.7 is end-of life since 2023-06-27.